# Generated by Django 2.2a1 on 2019-10-16 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20191016_2149'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='tasks',
            field=models.ManyToManyField(blank=True, to='main.Task'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='judge_id',
            field=models.CharField(max_length=30),
        ),
    ]
