# Generated by Django 2.2a1 on 2019-10-20 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_auto_20191020_1131'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='notes',
            field=models.ManyToManyField(blank=True, to='main.Note'),
        ),
    ]
