# Generated by Django 2.2a1 on 2019-11-04 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_auto_20191020_2132'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='task',
            field=models.CharField(max_length=60),
        ),
    ]
